/**
 * Copyright (C) 2015-2018 Philip Helger (www.helger.com)
 * philip[at]helger[dot]com
 *
 * The Original Code is Copyright The PEPPOL project (http://www.peppol.eu)
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package com.helger.peppol.smpserver.data.sql.model;

import java.io.Serializable;
import java.util.Set;

import javax.annotation.Nullable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.helger.db.jpa.annotation.UsedOnlyByJPA;
import com.helger.peppol.smp.ExtensionType;
import com.helger.peppol.smp.SMPExtensionConverter;

/**
 * ServiceGroup generated by hbm2java
 *
 * @author PEPPOL.AT, BRZ, Philip Helger
 */
@Entity
@Table (name = "smp_service_group")
public class DBServiceGroup implements Serializable
{
  private DBServiceGroupID m_aID;
  private String m_sExtension;
  private DBOwnership m_aOwnership;
  private Set <DBServiceMetadata> m_aServiceMetadatas;

  @Deprecated
  @UsedOnlyByJPA
  public DBServiceGroup ()
  {}

  public DBServiceGroup (final DBServiceGroupID aID,
                         final String sExtension,
                         final DBOwnership aOwnership,
                         final Set <DBServiceMetadata> aServiceMetadatas)
  {
    m_aID = aID;
    m_sExtension = sExtension;
    m_aOwnership = aOwnership;
    m_aServiceMetadatas = aServiceMetadatas;
  }

  @EmbeddedId
  public DBServiceGroupID getId ()
  {
    return m_aID;
  }

  @Deprecated
  @UsedOnlyByJPA
  public void setId (final DBServiceGroupID aID)
  {
    m_aID = aID;
  }

  @Lob
  @Column (name = "extension", length = 65535)
  public String getExtension ()
  {
    return m_sExtension;
  }

  public void setExtension (@Nullable final String sExtension)
  {
    m_sExtension = sExtension;
  }

  @Transient
  public void setExtension (@Nullable final ExtensionType aExtension)
  {
    setExtension (SMPExtensionConverter.convertToString (aExtension));
  }

  @OneToOne (fetch = FetchType.LAZY, mappedBy = "serviceGroup", cascade = { CascadeType.ALL })
  public DBOwnership getOwnership ()
  {
    return m_aOwnership;
  }

  public void setOwnership (final DBOwnership aOwnership)
  {
    m_aOwnership = aOwnership;
  }

  @OneToMany (fetch = FetchType.LAZY, mappedBy = "serviceGroup", cascade = { CascadeType.ALL })
  public Set <DBServiceMetadata> getServiceMetadatas ()
  {
    return m_aServiceMetadatas;
  }

  public void setServiceMetadatas (final Set <DBServiceMetadata> aServiceMetadatas)
  {
    m_aServiceMetadatas = aServiceMetadatas;
  }
}
