/**
 * Copyright (C) 2015-2019 Philip Helger and contributors
 * philip[at]helger[dot]com
 *
 * The Original Code is Copyright The PEPPOL project (http://www.peppol.eu)
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package com.helger.phoss.smp.backend.sql.model;

import java.io.Serializable;
import java.security.cert.X509Certificate;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Lob;
import javax.persistence.Table;

import com.helger.db.jpa.annotation.UsedOnlyByJPA;

/**
 * ServiceMetadataRedirection generated by hbm2java
 *
 * @author PEPPOL.AT, BRZ, Philip Helger
 */
@Entity
@Table (name = "smp_service_metadata_redirection")
public class DBServiceMetadataRedirection implements Serializable
{
  private DBServiceMetadataRedirectionID m_aID;
  private String m_sRedirectionUrl;
  private String m_sCertificateUid;
  private X509Certificate m_aCertificate;
  private String m_sExtension;

  @Deprecated
  @UsedOnlyByJPA
  public DBServiceMetadataRedirection ()
  {}

  public DBServiceMetadataRedirection (final DBServiceMetadataRedirectionID aID,
                                       final String sRedirectionUrl,
                                       final String sCertificateUid,
                                       final X509Certificate aCertificate,
                                       final String sExtension)
  {
    m_aID = aID;
    m_sRedirectionUrl = sRedirectionUrl;
    m_sCertificateUid = sCertificateUid;
    m_aCertificate = aCertificate;
    m_sExtension = sExtension;
  }

  @EmbeddedId
  public DBServiceMetadataRedirectionID getId ()
  {
    return m_aID;
  }

  @Deprecated
  @UsedOnlyByJPA
  public void setId (final DBServiceMetadataRedirectionID aID)
  {
    m_aID = aID;
  }

  @Column (name = "redirectionUrl", nullable = false, length = 256)
  public String getRedirectionUrl ()
  {
    return m_sRedirectionUrl;
  }

  public void setRedirectionUrl (final String sRedirectionUrl)
  {
    m_sRedirectionUrl = sRedirectionUrl;
  }

  @Column (name = "certificateUID", nullable = false, length = 256)
  public String getCertificateUid ()
  {
    return m_sCertificateUid;
  }

  public void setCertificateUid (final String sCertificateUid)
  {
    m_sCertificateUid = sCertificateUid;
  }

  @Lob
  @Column (name = "extension")
  public String getExtension ()
  {
    return m_sExtension;
  }

  public void setExtension (final String sExtension)
  {
    m_sExtension = sExtension;
  }

  // TODO JPA annotation
  public X509Certificate getCertificate ()
  {
    return m_aCertificate;
  }

  public void setCertificate (final X509Certificate aCertificate)
  {
    m_aCertificate = aCertificate;
  }
}
