# Use an official Tomcat runtime as a base image
FROM tomcat:9-jre11

# Special encoded slash handling for SMP
# Use non-blocking random
ENV CATALINA_OPTS="$CATALINA_OPTS -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true -Djava.security.egd=file:/dev/urandom"

# Install vim, Java 11 JDK, Maven and Git
RUN apt-get update \
  && apt-get install -y vim openjdk-11-jdk-headless git maven \
  && rm -rf /var/lib/apt/lists/*

# Remove predefined Tomcat webapps
RUN rm -r $CATALINA_HOME/webapps/ROOT \
  && rm -r $CATALINA_HOME/webapps/docs \
  && rm -r $CATALINA_HOME/webapps/examples

LABEL vendor="Philip Helger"
LABEL version="HEAD"
 
# Checkout from git and build
WORKDIR /home/git
RUN echo Building phoss SMP $SMP_VERSION \
  && git clone https://github.com/phax/phoss-smp.git . \
  && git checkout -b work \
  && mvn clean install -DskipTests

# Copy result to Tomcat webapps dir
RUN cp -r peppol-smp-server-webapp-xml/target/peppol-smp-server-webapp-xml-*/ $CATALINA_HOME/webapps/ROOT
